# Generated by Django 3.2.4 on 2021-10-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_feedback_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
