# Generated by Django 3.2.4 on 2021-10-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_feedback_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider_type',
            field=models.CharField(choices=[('google', 'Google'), ('guest', 'Guest'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('sapid_app', 'Sapid App')], default='sapid_app', max_length=20),
        ),
    ]
