version: "3.9"

services:
  web:
    build: .
    command: gunicorn sapid.wsgi:application -w 2 --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/code
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:8000"
    env_file:
      .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A sapid worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A sapid beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      

volumes:
  static_volume:
  media_volume:
