# Generated by Django 3.2.4 on 2021-10-06 05:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner-image')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'db_table': 'banner_image',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_favourites', models.PositiveIntegerField(default=0)),
                ('total_saves', models.PositiveIntegerField(default=0)),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='menu-image')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant-image')),
                ('address', models.CharField(max_length=1000)),
                ('landmark', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_favourites', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurant',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantAddExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_excel', models.FileField(upload_to='restaurant-excel', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'xlsm'])])),
            ],
            options={
                'verbose_name': 'Restaurant Add Excel',
                'verbose_name_plural': 'Restaurant Add Excels',
                'db_table': 'restaurant_excel',
            },
        ),
        migrations.CreateModel(
            name='SaveMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem')),
            ],
            options={
                'verbose_name': 'Save Menu Item',
                'verbose_name_plural': 'Save Menu Items',
                'db_table': 'save_menu_item',
            },
        ),
    ]
