# Generated by Django 3.2.4 on 2021-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['total_favourites'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='industry',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_or_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant-picture'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('name', 'city', 'zip_code')},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='logo',
        ),
    ]
