# Generated by Django 3.2.4 on 2021-10-07 04:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20211006_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantaddexcel',
            name='restaurant_excel',
            field=models.FileField(upload_to='restaurant-excel', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'xlsm', 'csv'])]),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menus',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='restaurant.menu'),
            preserve_default=False,
        ),
    ]
