# Generated by Django 3.2.4 on 2021-10-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20211007_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
    ]
