# Generated by Django 3.2.4 on 2021-10-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_menu_restaurant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('restaurant', 'menu', 'name')},
        ),
    ]
