# Generated by Django 3.2.4 on 2021-10-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20211013_0534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
    ]
