# Generated by Django 3.2.4 on 2021-10-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20211012_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_menu',
        ),
    ]
