# Generated by Django 3.2.4 on 2021-10-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_menuitem_unique_together'),
        ('restaurant', '0009_remove_menu_parent_menu'),
    ]

    operations = [
    ]
