# Generated by Django 3.2.4 on 2021-10-27 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_merge_20211018_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+918451234921'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Enter valid zipcode.')]),
        ),
    ]
