# Generated by Django 3.2.4 on 2021-10-27 09:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20211027_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='(e.g +918457221548)', max_length=128, null=True, region=None),
        ),
    ]
