# Generated by Django 3.2.4 on 2021-10-27 09:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_restaurant_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='(e.g +918457221548, +33123456789)', max_length=128, null=True, region=None),
        ),
    ]
