# Generated by Django 3.2.4 on 2021-10-28 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20211027_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, help_text='(e.g +91 8457221548, +33123456789)', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}[- ]?)?\\d{10}$', 'Please enter valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(help_text='(e.g 12021, 10001, 00979, 9790)', max_length=20, validators=[django.core.validators.RegexValidator('^(?!0{3})[0-9]{3,5}$', 'Please enter valid zip code.')]),
        ),
    ]
