# Generated by Django 3.2.4 on 2021-10-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20211028_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSearchText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Report Search Text',
                'verbose_name_plural': 'Report Search Texts',
                'db_table': 'report_search_text',
            },
        ),
    ]
