# Generated by Django 3.2.4 on 2021-10-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_reportsearchtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsearchtext',
            name='search_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
