# Generated by Django 3.2.4 on 2021-11-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20211123_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('menu',), 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
    ]
