# Generated by Django 3.2.4 on 2022-02-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_auto_20211209_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(max_length=20),
        )
    ]
