# Generated by Django 3.2.4 on 2022-02-25 12:07

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_auto_20220225_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hidden_address',
            field=mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True, verbose_name='Location'),
        ),
    ]
