# Generated by Django 3.2.4 on 2022-03-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_restaurantaddresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='hidden_address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
    ]
